version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: habit_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: habit_tracker_db
      POSTGRES_USER: habit_user
      POSTGRES_PASSWORD: habit_pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
